version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app-node:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    command: npm run start:dev
    tty: true
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network
    volumes:
      - .:/app

  db-app:
    image: postgres:15.2
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
      - ./.docker/sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
